// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package org.xiaofu.tri;

public final class GreeterOuterClass {
  private GreeterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaofu_tri_GreeterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_xiaofu_tri_GreeterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaofu_tri_GreeterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_xiaofu_tri_GreeterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgreeter.proto\022\016org.xiaofu.tri\"\036\n\016Greet" +
      "erRequest\022\014\n\004name\030\001 \001(\t\"\037\n\014GreeterReply\022" +
      "\017\n\007message\030\001 \001(\t2\366\001\n\007Greeter\022E\n\005greet\022\036." +
      "org.xiaofu.tri.GreeterRequest\032\034.org.xiao" +
      "fu.tri.GreeterReply\022S\n\021greetServerStream" +
      "\022\036.org.xiaofu.tri.GreeterRequest\032\034.org.x" +
      "iaofu.tri.GreeterReply0\001\022O\n\013greetStream\022" +
      "\036.org.xiaofu.tri.GreeterRequest\032\034.org.xi" +
      "aofu.tri.GreeterReply(\0010\001B\022\n\016org.xiaofu." +
      "triP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_xiaofu_tri_GreeterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_xiaofu_tri_GreeterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_xiaofu_tri_GreeterRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_xiaofu_tri_GreeterReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_xiaofu_tri_GreeterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_xiaofu_tri_GreeterReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
